//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data;

    public partial class tblRegistration
    {
        public int id { get; set; }

        [Display(Name = "Date")]
        [Required(ErrorMessage = "Enter Date!")]
        public System.DateTime Date { get; set; }

        [Display(Name = "Time")]
        [Required(ErrorMessage = "Enter Current Time!")]
        public System.TimeSpan Time { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Enter Full Name!")]
        public string Name { get; set; }

        [Display(Name = "District")]
        [Required(ErrorMessage = "Enter Your District!")]
        public string District { get; set; }

        [Display(Name = "Taluka")]
        [Required(ErrorMessage = "Enter Your Taluka!")]
        public string Taluka { get; set; }

        [Display(Name = "Village")]
        [Required(ErrorMessage = "Enter Your Village!")]
        public string Village { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        public string Phone_No { get; set; }

        [Required(ErrorMessage = "Enter Your Request here!")]
        public string Request_For { get; set; }

        [Required(ErrorMessage = "Enter How many Live Stock you have!")]
        public int No_of_Livestock { get; set; }
    }
}
