//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVillage
    {
        public int VillageId { get; set; }
        public string VillageName { get; set; }
    }
}
